import { LINES } from '@/lib/lines'
import type { Product, Article } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: 'menopausa-complex',
    name: 'Menopausa Complex',
    line: LINES.menopausa,
    shortDescription:
      'Supporto naturale al benessere femminile nel periodo della menopausa, con ingredienti botanici selezionati.',
    longDescription:
      'Menopausa Complex è una formula botanica d\'eccellenza pensata per accompagnare la donna durante la menopausa. Il blend di isoflavoni di soia, cimicifuga e salvia agisce in sinergia per favorire il benessere quotidiano e il riequilibrio naturale.',
    ingredients: [
      { name: 'Isoflavoni di Soia', dosage: '40 mg' },
      { name: 'Cimicifuga e.s. 2,5% triterpeni', dosage: '20 mg' },
      { name: 'Salvia e.s. 1,5% acido rosmarinico', dosage: '150 mg' },
      { name: 'Magnesio bisglicinato', dosage: '100 mg' },
      { name: 'Vitamina B6', dosage: '1,4 mg' },
    ],
    usage: 'Si consiglia l\'assunzione di 2 capsule al giorno, preferibilmente ai pasti, con un bicchiere d\'acqua.',
    target:
      'Pensato per le donne in fase di perimenopausa e menopausa che desiderano un supporto naturale al benessere quotidiano.',
    format: 'Capsule vegetali',
    capsules: 60,
    days: 30,
    dosage: '2 capsule/die',
    notificationMs: 'Notif. Min. Salute',
    images: {
      fronte:      '/products/menopausa-complex/fronte.png',
      infografica: '/products/menopausa-complex/infografica.png',
      lato1:       '/products/menopausa-complex/lato-1.png',
      lato2:       '/products/menopausa-complex/lato-2.png',
    },
    published: true,
    order: 1,
  },
  {
    id: '2',
    slug: 'capelli-pelle-unghie',
    name: 'Capelli, Pelle & Unghie',
    line: LINES.beauty,
    shortDescription:
      'Formula nutrizionale mirata con Mela Annurca, Biotina, Bamboo 70% silice e Astaxantina 2,5% per capelli forti, pelle luminosa e unghie sane.',
    longDescription:
      'Un complesso nutrizionale avanzato che combina aminoacidi strutturali (L-Cisteina, L-Metionina), attivi antiossidanti (Astaxantina, Vitamina C, Selenio) e micronutrienti essenziali (Biotina, Zinco, Ferro, Vitamina B12) per un supporto completo alla salute di capelli, pelle e unghie dall\'interno.',
    ingredients: [
      { name: 'Mela annurca e.s.', dosage: '200 mg' },
      { name: 'L-Cisteina', dosage: '140 mg' },
      { name: 'L-Metionina', dosage: '140 mg' },
      { name: 'Acido Ascorbico (Vit. C)', dosage: '80 mg' },
      { name: 'Bamboo e.s. titolato 70% silice', dosage: '60 mg' },
      { name: 'Niacina (Vit. B3)', dosage: '40 mg' },
      { name: 'Ferro', dosage: '30 mg' },
      { name: 'Vitamina B6', dosage: '10 mg' },
      { name: 'Zinco', dosage: '10 mg' },
      { name: 'Ematococcus pluvialis e.s. tit. astaxantina 2,5%', dosage: '6 mg' },
      { name: 'Rame', dosage: '2 mg' },
      { name: 'Vitamina B12', dosage: '500 mcg' },
      { name: 'Biotina', dosage: '450 mcg' },
      { name: 'Acido Folico', dosage: '200 mcg' },
      { name: 'Selenio', dosage: '50 mcg' },
    ],
    usage: 'Si consiglia l\'assunzione di 2 capsule al giorno, da deglutire con un bicchiere d\'acqua.',
    target:
      'Per chi desidera rafforzare capelli e unghie fragili e migliorare la luminosità della pelle attraverso un supporto nutrizionale mirato. Adatto a partire dai 12 anni.',
    format: '60 capsule vegetali · 750 mg · Senza glutine · Naturalmente privo di lattosio · Adatto ai vegani e vegetariani · No OGM · Senza zuccheri aggiunti',
    capsules: 60,
    days: 30,
    dosage: '2 capsule/die',
    notificationMs: 'Min. Salute N. 197030',
    images: {
      fronte:      '/products/capelli-pelle-unghie/fronte.png',
      infografica: '/products/capelli-pelle-unghie/infografica.png',
      lato1:       '/products/capelli-pelle-unghie/lato-1.png',
      lato2:       '/products/capelli-pelle-unghie/lato-2.png',
    },
    published: true,
    order: 2,
  },
  {
    id: '3',
    slug: 'microcircolo-superior',
    name: 'Microcircolo Superior',
    line: LINES.circolo,
    shortDescription:
      'Complesso flavonoico avanzato con Diosmina ultramicronizzata, Esperidina micronizzata, Bromelina 10.000 GDU gastroprotetta ed estratti vegetali.',
    longDescription:
      'Integratore alimentare a base di Diosmina, Esperidina, Bromelina 10.000 GDU ed estratti vegetali di Centella, Rusco e Uva rossa. La Centella, il Rusco e l\'Uva rossa favoriscono la funzionalità del microcircolo (pesantezza delle gambe). Il Rusco contribuisce alla funzionalità della circolazione venosa (funzionalità del plesso emorroidario). L\'Uva rossa favorisce la regolare funzionalità dell\'apparato cardiovascolare e ha un\'azione antiossidante.',
    ingredients: [
      { name: 'Diosmina ultramicronizzata', dosage: '900 mg' },
      { name: 'Esperidina micronizzata', dosage: '100 mg' },
      { name: 'Bromelina 10.000 GDU/g gastroprotetta', dosage: '100 mg (1000 GDU*)' },
      { name: 'Rusco e.s. tit. 20% in ruscogenine', dosage: '100 mg' },
      { name: 'Uva rossa e.s. tit. 95% in OPC', dosage: '100 mg' },
      { name: 'Centella e.s. tit. 40% in asiaticosidi', dosage: '60 mg' },
    ],
    usage: 'Si consiglia l\'assunzione di 2 capsule al giorno, preferibilmente a stomaco vuoto.',
    target:
      'Adulti che desiderano supportare la funzionalità del microcircolo e la normale circolazione venosa. Indicato in particolare per chi avverte pesantezza alle gambe, soprattutto nei periodi caldi o dopo molte ore in piedi.',
    format: '60 capsule vegetali · 750 mg · Senza glutine · Naturalmente privo di lattosio · Adatto ai vegani e vegetariani · No OGM · Senza zuccheri aggiunti',
    capsules: 60,
    days: 30,
    dosage: '2 capsule/die',
    notificationMs: 'Min. Salute N. 209822',
    images: {
      fronte:      '/products/microcircolo-superior/fronte.png',
      infografica: '/products/microcircolo-superior/infografica.png',
      lato1:       '/products/microcircolo-superior/lato-1.png',
      lato2:       '/products/microcircolo-superior/lato-2.png',
      etichetta:   '/products/microcircolo-superior/etichetta.png',
    },
    published: true,
    order: 3,
  },
  {
    id: '4',
    slug: 'multivitaminico-minerali',
    name: 'Multivitaminico & Minerali',
    line: LINES.energia,
    shortDescription:
      'Complesso nutrizionale avanzato con oltre 20 vitamine, minerali e antiossidanti selezionati.',
    longDescription:
      'Una formula completa con Vitamina C liposomiale ad alta biodisponibilità, CoQ10, Pterostilbene e Acetil L-carnitina. Integra Vitamina D3 da lichene, Magnesio bisglicinato e un pannello completo di vitamine del gruppo B per un supporto energetico quotidiano.',
    ingredients: [
      { name: 'Vitamina C liposomiale', dosage: '200 mg' },
      { name: 'CoQ10 (Ubichinone)', dosage: '100 mg' },
      { name: 'Pterostilbene', dosage: '50 mg' },
      { name: 'Acetil L-carnitina', dosage: '250 mg' },
      { name: 'Vitamina D3 da lichene', dosage: '25 µg (1000 UI)' },
      { name: 'Magnesio bisglicinato', dosage: '150 mg' },
      { name: 'Zinco', dosage: '10 mg' },
      { name: 'Complesso vitamine B', dosage: 'da B1 a B12' },
    ],
    usage: 'Si consiglia l\'assunzione di 1 capsula al giorno, preferibilmente al mattino ai pasti, con un bicchiere d\'acqua.',
    target: 'Per adulti dai 13 anni che desiderano un supporto nutrizionale completo all\'energia quotidiana.',
    format: 'Capsule vegetali',
    capsules: 30,
    days: 30,
    dosage: '1 capsula/die',
    minAge: 13,
    published: true,
    order: 4,
  },
]

export const ARTICLES: Article[] = [
  {
    id: '1',
    slug: 'coq10-pterostilbene-sinergia-anti-aging',
    title: 'CoQ10 e Pterostilbene: la sinergia anti-aging spiegata dalla ricerca scientifica',
    excerpt:
      'Due molecole, un obiettivo: rallentare i processi ossidativi cellulari. Ecco cosa dice la letteratura più recente.',
    body: 'La combinazione di CoQ10 e Pterostilbene rappresenta una delle frontiere più promettenti della nutraceutica moderna...',
    tag: 'Scienza',
    publishedAt: '2026-06-12',
    readingTime: 5,
    published: true,
  },
  {
    id: '2',
    slug: 'mela-annurca-superfood-italiano',
    title: 'Mela Annurca: il superfood italiano per capelli forti e pelle luminosa',
    excerpt: 'Un frutto della tradizione campana diventato protagonista della nutraceutica moderna.',
    body: 'La Mela Annurca è una varietà autoctona campana con la più alta concentrazione di procianidine...',
    tag: 'Nutrizione',
    publishedAt: '2026-06-05',
    readingTime: 4,
    published: true,
  },
  {
    id: '3',
    slug: 'gambe-pesanti-microcircolo-estate',
    title: 'Gambe pesanti in estate: come supportare il microcircolo giorno per giorno',
    excerpt: 'Il caldo aumenta la sensazione di pesantezza. Scopri i meccanismi e le strategie di supporto.',
    body: 'Nelle stagioni calde, la vasodilatazione periferica può accentuare la sensazione di gambe pesanti...',
    tag: 'Benessere',
    publishedAt: '2026-05-28',
    readingTime: 3,
    published: true,
  },
  {
    id: '4',
    slug: 'vitamina-c-liposomiale-biodisponibilita',
    title: 'Vitamina C liposomiale vs tradizionale: perché la biodisponibilità cambia tutto',
    excerpt: 'Non tutta la Vitamina C è uguale. La forma liposomiale raggiunge le cellule in modo radicalmente diverso.',
    body: 'La Vitamina C tradizionale (acido ascorbico) ha una biodisponibilità limitata dall\'assorbimento intestinale...',
    tag: 'Scienza',
    publishedAt: '2026-05-20',
    readingTime: 6,
    published: true,
  },
]
